### ISSUE TITLE
How to get orders?

### ISSUE THREAD

**Issue by crissrocca** [louismerlin/binance-bot#3]
Thanks for the .js.

I don't understand the need to use the YOU ID, can I use it without that ID?
How can I do, to automatically send the operations in FUTURES o SPOT? for example, I make a LONG or SHORT in futures and it shows in the telegram with all data.

Regards from Basêl :octocat:

**Comment by louismerlin** [comment]
This program is 3 years old, the APIs may have changed since then. I have not kept the program up to date.

- Regarding the "you" field, I think it is inevitable if you want only yourself to receive the messages. Otherwise, anyone could subscribe to these notifications.
- Regarding the *futures* and *spot*, you could add an `else if` on line **47** that catches these kinds of events, and sends you a message with all of the relevant data.

**Comment by crissrocca** [comment]
Thank you for your quick answer.
To let it work on a server, once the files are uploaded, do I need to execute a call so that the Telegram receives the notices? Set up a cronjobs or something?

Regards,

**Comment by louismerlin** [comment]
You need to launch the bot with `node index.js` on your server, and this should suffice. But again, I have not idea if that bot still works.

**Comment by crissrocca** [comment]
ok, thank's

XXX
